// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sywifwbitztxghdkxmuy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN5d2lmd2JpdHp0eGdoZGt4bXV5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4NDY5NDEsImV4cCI6MjA2NTQyMjk0MX0.AZOuHbyH7xu5wnbQcpFe5ht8GVxe2mD8Lab0i9zouNE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);